[package]
name = "neon-fibonacci"
version = "0.1.0"
authors = ["nswbmw"]
license = "MIT"
build = "build.rs"

[lib]
name = "neon_fibonacci"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.13"

[dependencies]
neon = "0.1.13"

[profile.release]
opt-level = 3